function Event() {
    this.DEFAULT_FILE_LOADED = "DEFAULT_FILE_LOADED";
    this.GENERATED_FILE_LOADED = "GENERATED_FILE_LOADED";
    this.RENDER_REQUESTED = "RENDER_REQUESTED";
    this.CONFIG_UPDATED = "CONFIG_UPDATED";
    this.PROPERTIES_ADDED = "PROPERTIES_ADDED";
    this.PROPERTIES_REMOVED = "PROPERTIES_REMOVED";
    this.DEFINITION_USED = "DEFINITION_USED";
    this.DEFINITION_UNUSED = "DEFINITION_UNUSED";
    this.DEFINITION_ADDED = "DEFINITION_ADDED";
    this.MODEL_RENDER_REQUESTED = "MODEL_RENDER_REQUESTED";
    this.ADVANCED_CONFIG_UPDATED = "ADVANCED_CONFIG_UPDATED";
}